name: "dbt_col"
version: "0.1.0"
require-dbt-version: [">=1.0.0", "<2.0.0"]
config-version: 2

profile: "dbt_col"

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Automatic hook - runs automatically when package is installed
on-run-end:
  - "{{ dbt_col.on_run_end() }}"

models:
  dbt_col:
    +materialized: table 